### ISSUE TITLE
TESTING: for sign off

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#4]
TESTING: for sign off

**Comment by status-open-bounty** [comment]
Current balance: 0.000988 ETH
Contract address: [0xac9b949d358b0b5d62e3681f8cd7f29ac3f6e02c](https://ropsten.etherscan.io/address/0xac9b949d358b0b5d62e3681f8cd7f29ac3f6e02c)
![QR Code](https://testing.openbounty.status.im/qr/TestingEnvENV/TestEnvAtt5/bounty/4/3fa14a6f96acb77a55f27d8977038b5ea36406b32d2b8380ff5d609913b993b1/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://testing.openbounty.status.im](https://testing.openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
